
package ru.terralink.regnumservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IRegNumberService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IRegNumberService {


    /**
     * 
     * @param tags
     * @param reserve
     * @param comment
     * @param templateName
     * @return
     *     returns ru.terralink.regnumservice.RegNumberRest
     */
    @WebMethod(operationName = "Next", action = "http://tempuri.org/IRegNumberService/Next")
    @WebResult(name = "NextResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Next", targetNamespace = "http://tempuri.org/", className = "ru.terralink.regnumservice.Next")
    @ResponseWrapper(localName = "NextResponse", targetNamespace = "http://tempuri.org/", className = "ru.terralink.regnumservice.NextResponse")
    public RegNumberRest next(
        @WebParam(name = "TemplateName", targetNamespace = "http://tempuri.org/")
        String templateName,
        @WebParam(name = "Tags", targetNamespace = "http://tempuri.org/")
        ArrayOfKeyValueOfstringstring tags,
        @WebParam(name = "Reserve", targetNamespace = "http://tempuri.org/")
        Boolean reserve,
        @WebParam(name = "Comment", targetNamespace = "http://tempuri.org/")
        String comment);

    /**
     * 
     * @param tags
     * @param templateName
     * @return
     *     returns ru.terralink.regnumservice.ArrayOfRegNumberRest
     */
    @WebMethod(operationName = "Reserved", action = "http://tempuri.org/IRegNumberService/Reserved")
    @WebResult(name = "ReservedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Reserved", targetNamespace = "http://tempuri.org/", className = "ru.terralink.regnumservice.Reserved")
    @ResponseWrapper(localName = "ReservedResponse", targetNamespace = "http://tempuri.org/", className = "ru.terralink.regnumservice.ReservedResponse")
    public ArrayOfRegNumberRest reserved(
        @WebParam(name = "TemplateName", targetNamespace = "http://tempuri.org/")
        String templateName,
        @WebParam(name = "Tags", targetNamespace = "http://tempuri.org/")
        ArrayOfKeyValueOfstringstring tags);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "Fix", action = "http://tempuri.org/IRegNumberService/Fix")
    @WebResult(name = "FixResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Fix", targetNamespace = "http://tempuri.org/", className = "ru.terralink.regnumservice.Fix")
    @ResponseWrapper(localName = "FixResponse", targetNamespace = "http://tempuri.org/", className = "ru.terralink.regnumservice.FixResponse")
    public Boolean fix(
        @WebParam(name = "Id", targetNamespace = "http://tempuri.org/")
        Integer id);

}
