
package ru.terralink.regnumservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @param tags
     * @param reserve
     * @param comment
     * @param templateName
     * @return
     *     returns ru.terralink.regnumservice.RegNumber
     */
    @WebMethod(operationName = "Next", action = "http://tempuri.org/IService/Next")
    @WebResult(name = "NextResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Next", targetNamespace = "http://tempuri.org/", className = "ru.terralink.regnumservice.Next")
    @ResponseWrapper(localName = "NextResponse", targetNamespace = "http://tempuri.org/", className = "ru.terralink.regnumservice.NextResponse")
    public RegNumber next(
            @WebParam(name = "templateName", targetNamespace = "http://tempuri.org/")
            String templateName,
            @WebParam(name = "tags", targetNamespace = "http://tempuri.org/")
            ArrayOfKeyValueOfstringstring tags,
            @WebParam(name = "reserve", targetNamespace = "http://tempuri.org/")
            Boolean reserve,
            @WebParam(name = "comment", targetNamespace = "http://tempuri.org/")
            String comment);

    /**
     *
     * @param id
     */
    @WebMethod(operationName = "Fix", action = "http://tempuri.org/IService/Fix")
    @RequestWrapper(localName = "Fix", targetNamespace = "http://tempuri.org/", className = "ru.terralink.regnumservice.Fix")
    @ResponseWrapper(localName = "FixResponse", targetNamespace = "http://tempuri.org/", className = "ru.terralink.regnumservice.FixResponse")
    public void fix(
            @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
            Integer id);

}
